version: 1.0
stages:
- StageOne
jobs:
  fdsafads:
    description: ''
    type: source-checkout
    stage: StageOne
    context:
    - fdas
    - fdsa
    timeout: 30
    priority: major
    parameters:
      branch: codeminefile
